### ISSUE TITLE
unable to guess the VisDA-2017 dataset structure for semantic segmentation task

### ISSUE THREAD

**Issue by vamsikrishna7909** [LeapLabTHU/DAPrompt#7]
Hi there,

I am trying to run this project in my machine to experiment something. I setup the project and I wanted to train it with VisDA-2017 segmentation datasets like GTA5 and Cityscapes. But the script is expecting something and I'm not sure.

Here is the issue:

`Loading trainer: DAPL
Loading dataset: VisDA17
Traceback (most recent call last):
  File "train.py", line 208, in <module>
    main(args)
  File "train.py", line 127, in main
    trainer = build_trainer(cfg)
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/engine/trainer.py", line 324, in __init__
    self.build_data_loader()
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/engine/trainer.py", line 347, in build_data_loader
    dm = DataManager(self.cfg)
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/data/data_manager.py", line 61, in __init__
    dataset = build_dataset(cfg)
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/data/datasets/build.py", line 11, in build_dataset
    return DATASET_REGISTRY.get(cfg.DATASET.NAME)(cfg)
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/data/datasets/da/visda17.py", line 31, in __init__
    train_x = self._read_data("synthetic")
  File "/home/008458886@csusb.edu/ENTER/envs/dassl/lib/python3.8/site-packages/dassl/data/datasets/da/visda17.py", line 44, in _read_data
    with open(image_list, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/vamsi_project/da_prompt_repo/DAPrompt/data/visda17/train/image_list.txt'
^C

(dassl) :/vamsi_project/da_prompt_repo/DAPrompt/scripts$ cd ..
(dass)/vamsi_project/da_prompt_repo/DAPrompt$ cd data
(dassl) :/vamsi_project/da_prompt_repo/DAPrompt/data$ ls
get_gta.sh  real  synthetic  test_data  test.zip
(dassl) /vamsi_project/da_prompt_repo/DAPrompt/data$ cd real
(dassl):/vamsi_project/da_prompt_repo/DAPrompt/data/real$ ls
cookie.txt  gtFine  leftImg8bit
(dassl) /vamsi_project/da_prompt_repo/DAPrompt/data/real$ cd ..
(dassl) :/vamsi_project/da_prompt_repo/DAPrompt/data$ cd synthetic/
(dassl) :/vamsi_project/da_prompt_repo/DAPrompt/data/synthetic$ ls
extract_gta5_from_scratch.sh  extraction_log.txt  images  labels  mapping.mat  readImage.m  split.mat`

Please let me know

**Comment by John-Ge** [comment]
Our project only supports classification now.

**Comment by vamsikrishna7909** [comment]
Oh! yeah. Thanks for clarification. I thought we can use this experiment for segmentation track as well.

Thanks again for your prompt response. I really appreciate it.

**Comment by John-Ge** [comment]
Maybe some papers following our work develop method for segmentation. You could check it.

**Comment by vamsikrishna7909** [comment]
Okay. I'll start researching on it. Thanks!

By the way, I'm trying to run this project using VisDA-2017 classification dataset. I downloaded the datasets as suggested in readme.

when I try to run the train command, I'm getting the below response.
`(dassl) vamsi_project/da_prompt_repo/DAPrompt/scripts$ bash main.sh visda17 ep25-32-csc 1.0 0.5 1.0 t0
Results are available in output/visda17/DAPL/ep25-32-csc/1.0_0.5_1.0_t0/seed_1. Skip this job
Results are available in output/visda17/DAPL/ep25-32-csc/1.0_0.5_1.0_t0/seed_2. Skip this job
Results are available in output/visda17/DAPL/ep25-32-csc/1.0_0.5_1.0_t0/seed_3. Skip this job
Results are available in output/visda17/DAPL/ep25-32-csc/1.0_0.5_1.0_t0/seed_4. Skip this job
Results are available in output/visda17/DAPL/ep25-32-csc/1.0_0.5_1.0_t0/seed_5. Skip this job




`
<img width="1435" alt="Screenshot 2024-10-18 at 12 40 52 AM" src="https://github.com/user-attachments/assets/77f6c478-dade-4f2d-9528-c936c84b4e0b">
<img width="529" alt="Screenshot 2024-10-18 at 12 41 32 AM" src="https://github.com/user-attachments/assets/ca22d775-fa68-4547-b364-47a596348467">
<img width="479" alt="Screenshot 2024-10-18 at 12 41 53 AM" src="https://github.com/user-attachments/assets/1e87398c-6785-4151-809f-e0bbd1d8041c">


when I go and see log files. I don't know what's missing. Please let me know.

**Comment by vamsikrishna7909** [comment]
Never mind, I got to clear the previous log files.
